### PR TITLE
chore(programs): Add `bin` directory to `.gitignore`

### PR DESCRIPTION
**Pull request by vadorovsky**

### CODE REVIEW

**Comment by ananas-block** [comment]
why do we have a bin folder in light-system programs?

**Comment by vadorovsky** [comment]
> why do we have a bin folder in light-system programs?

Because `yarn build` creates them. I actually don't fully understand why

https://github.com/Lightprotocol/light-protocol/blob/66c8ad936ae11e6d73f88f582dfdf90cfd0e92a6/light-system-programs/package.json#L5

https://github.com/Lightprotocol/light-protocol/blob/3d7f4f23749dde4c0fafe8b62a5ed74366f44a96/cli/scripts/copyLocalProgramBinaries.sh#L9

**Comment by ananas-block** [comment]
Oh that's a bug yarn build should copy them to cli's bin folder

**Comment by ananas-block** [comment]
What do you think about editing cli/script/copyLocalBinaries.sh:
```
cd ..
for key in $keys
do
    cp light-system-programs/target/deploy/$key.so cli/bin/$key.so
done

cp test-env/programs/spl_noop.so cli/bin/spl_noop.so
cd -
```

**Comment by vadorovsky** [comment]
> What do you think about editing cli/script/copyLocalBinaries.sh:
> 
> ```
> cd ..
> for key in $keys
> do
>     cp light-system-programs/target/deploy/$key.so cli/bin/$key.so
> done
> 
> cp test-env/programs/spl_noop.so cli/bin/spl_noop.so
> cd -
> ```

Sounds good to me, will try to do that later today.

**Pull request closed without merging**
