### PR TITLE
fix: cli program bin download, test-validator background flag

### PR DESCRIPTION
**Pull request by ananas-block**
- binary download fix is already part of the last cli release
- the test validator background flag is not part of the last release

### CODE REVIEW

**Comment by vadorovsky** [comment]
I don't think that the PR title is accurate? I see mostly changes related to fixing `light test-validator`.

**Comment by ananas-block** [comment]
> I don't think that the PR title is accurate? I see mostly changes related to fixing `light test-validator`.

you are right the bin download fix is just this line:
https://github.com/Lightprotocol/light-protocol/pull/236/files#diff-ae098510c28e4ea810a9c0f3b0a070fccdd83301a3e2d7c424896ca2fb2474c2R89

**Review by vadorovsky — CHANGES_REQUESTED** [review]
I would rather not merge this PRs, as it contains 3 completely unrelated changes:

* fixing the solana-test-validator command
* fixing 
* version bump (which I don't think is needed now)

Given that @ananas-block is on vacation, I think the best was to proceed is if I take over and try to push the first two points as separate PRs, while acknowledging @ananas-block as an author or co-author.

**Comment by ananas-block** [comment]
@vadorovsky have the changes in this pr already been merged in others?

**Comment by vadorovsky** [comment]
> @vadorovsky have the changes in this pr already been merged in others?

no, sorry :(

**Comment by ananas-block** [comment]
> I would rather not merge this PRs, as it contains 3 completely unrelated changes:
> 
>     * fixing the solana-test-validator command
> 
>     * changing the bin directories
> 
>     * version bump (which I don't think is needed now)
> 
> 
> Given that @ananas-block is on vacation, I think the best was to proceed is if I take over and try to push the first two points as separate PRs, while acknowledging @ananas-block as an author or co-author.

- Where are bin directories being changed?
- The version bump was necessary because I made a release.
- The bin download fix is additional waiting time. Prior to this pr the download time of spl program binaries counted into the waiting time for the test validator to launch. This produced situations during which the test validator was not completely running but the waiting time already expired.

**Comment by ananas-block** [comment]
I see that in retrospect the description could have been more clear

**Review by vadorovsky — APPROVED** [review]

**Pull request merged**
