### PR TITLE
test: Invalid Merkle tree updates

### PR DESCRIPTION
**Pull request by vadorovsky**
Test Merkle tree updates always with one parameter slightly broken and the rest of parameters being correct. The parameters are:

* Changelog indes
* Old leaf
* Leaf index
* Merkle proof

This way we make sure that validating all of them works.

### CODE REVIEW

**Comment by ananas-block** [comment]
Which of the parameters is always broken?
(I don't see a fix in this pr)

**Comment by vadorovsky** [comment]
> Which of the parameters is always broken? (I don't see a fix in this pr)

Look at the `invalid_updates` function - it takes the correct parameters, but then always swaps each parameter and tries to update, then asserts a failure.

The only commented case is `changelog_index` swap, but we can uncomment it once #699 gets in.

There are no bugfixes in this PR, just more tests.

**Comment by ananas-block** [comment]
https://github.com/Lightprotocol/light-protocol/pull/699 is merged you can uncomment

**Comment by vadorovsky** [comment]
> #699 is merged you can uncomment else looks good

Uncommented

**Pull request merged**
