### PR TITLE
chore: indexed merkle tree emit two changelog entries at init

### PR DESCRIPTION
**Pull request by ananas-block**
Issue:
- in indexed Merkle tree the changelog indices between the Merkle tree changelog and the indexed changelog are different by 1
- this pr emits a second indexed changelog for consistency

### CODE REVIEW

**Comment by vadorovsky** [comment]
I don't get it. Why exactly is having different changelog indices an issue? Eventually they are going to differ anyway, since CMT changelog and indexed changelog have different modulus.

Also, pushing the same changelog entry twice just feels incorrect.

**Comment by ananas-block** [comment]
in the forester we need to derive both the changelog and the indexed changelog from the sequence number we get from the indexer.
On current main we need to changelog = `indexer_request.root_index % 1400` indexed_changelog = `indexer_request.root_index -1 % 256`
The `-1` feels wrong in a similar way you describe.
The reasoning was that emitting two changelogs here is consistent with concurrent Merkle tree which emits a changelog at intialization and then one at append. However, we just emit one indexed changelog in indexed Merkle tree so actually the right way in my opinion would be to remove the changelog from concurrent Merkle tree. That however makes unit tests fail hence the intuition to just make it consistent and avoid footguns in the forester which is more likely to change in the future than the indexed Merkle tree.

**Comment by vadorovsky** [comment]
> On current main we need to changelog = `indexer_request.root_index % 1400` indexed_changelog = `indexer_request.root_index -1 % 256` The `-1` feels wrong in a similar way you describe.

I see.

That could be easily avoided if we included changelog indices in events and made Photon aware of them. But sadly, it's way too late to do that. Lesson for the future to not rely on `seq` for everything and to think of including more information in events.

**Review by vadorovsky — APPROVED** [review]
approving with saddness 😬

**Comment by ananas-block** [comment]
thanks!
agreed its ugly

**Pull request merged**
